per_page:
  users_index: 20
  product_index: 18
one: "1"
users:
  name:
    maximum: 50
  email:
    maximum: 255
  password:
    minimum: 6
gravatar:
  size: 80
  index_size: 50

truncate:
  name: 30
  description: 70
